### ISSUE TITLE
Check guix.carldong.io

### ISSUE THREAD

**Issue by pinheadmz** [fanquake/core-review#35]
Error from docker using the `--buil-args` instructions:

`7.403 wget: can't connect to remote host (4.53.92.115): Connection refused`

That's Carl's IP:

```
--> dig guix.carldong.io +short
4.53.92.115
```

Simpler docker build command seems to work OK

**Comment by fanquake** [comment]
Thanks. Have swapped this out of the example for using the GUIX mirror link in https://github.com/fanquake/core-review/commit/e8d0e049f24e59b785858c74c45caf365f0113c5. Which will pick a random mirror.
