### ISSUE TITLE
alpine issues

### ISSUE THREAD

**Issue by tofutim** [fanquake/core-review#37]
```
 => ERROR [3/7] RUN git clone https://github.com/bitcoin/bitcoin && mkdir bitcoin/depends/SDKs                                                  171.0s 
------                                                                                                                                                 
 > [3/7] RUN git clone https://github.com/bitcoin/bitcoin && mkdir bitcoin/depends/SDKs:                                                               
0.224 Cloning into 'bitcoin'...                                                                                                                        
170.9 error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)                                                                
170.9 error: 339 bytes of body are still expected                                                                                                      
170.9 fetch-pack: unexpected disconnect while reading sideband packet
170.9 fatal: early EOF
170.9 fatal: fetch-pack: invalid index-pack output
------
Dockerfile:33
--------------------
  31 |         zeromq-dev
  32 |     
  33 | >>> RUN git clone https://github.com/bitcoin/bitcoin && mkdir bitcoin/depends/SDKs
  34 |     
  35 |     RUN make download -C bitcoin/depends
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone https://github.com/bitcoin/bitcoin && mkdir bitcoin/depends/SDKs" did not complete successfully: exit code: 128
```
Internet too slow?

**Comment by tofutim** [comment]
Must have been me. Works now.

**Comment by allysa08** [comment]
> ```
>  => ERROR [3/7] RUN git clone https://github.com/bitcoin/bitcoin && mkdir bitcoin/depends/SDKs                                                  171.0s 
> ------                                                                                                                                                 
>  > [3/7] RUN git clone https://github.com/bitcoin/bitcoin && mkdir bitcoin/depends/SDKs:                                                               
> 0.224 Cloning into 'bitcoin'...                                                                                                                        
> 170.9 error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)                                                                
> 170.9 error: 339 bytes of body are still expected                                                                                                      
> 170.9 fetch-pack: unexpected disconnect while reading sideband packet
> 170.9 fatal: early EOF
> 170.9 fatal: fetch-pack: invalid index-pack output
> ------
> Dockerfile:33
> --------------------
>   31 |         zeromq-dev
>   32 |     
>   33 | >>> RUN git clone https://github.com/bitcoin/bitcoin && mkdir bitcoin/depends/SDKs
>   34 |     
>   35 |     RUN make download -C bitcoin/depends
> --------------------
> ERROR: failed to solve: process "/bin/sh -c git clone https://github.com/bitcoin/bitcoin && mkdir bitcoin/depends/SDKs" did not complete successfully: exit code: 128
> ```
> Internet too slow?
