### ISSUE TITLE
no guix?

### ISSUE THREAD

**Issue by tofutim** [fanquake/core-review#38]
I am experimenting with your alpine_guix image, and running into an issue where guix seems to not be installed. Any tips?
```
tim@saba:~$ docker exec -it alpine_guix /bin/bash
2d0ac17e5752:/bitcoin# time BASE_CACHE="/base_cache" SOURCE_PATH="/sources" SDK_PATH="/SDKs" HOSTS="x86_64-w64-mingw32" ./contrib/guix/guix-build
ERR: This script requires that 'guix' is installed and available in your $PATH

real	0m0.018s
user	0m0.008s
sys	0m0.011s
```

**Comment by tofutim** [comment]
I don't know how I even made 'alpine_guix' will restart.

**Comment by joeyvee1986** [comment]
I be like a mad scientist up In here tonight.

**Comment by tofutim** [comment]
Happy Thanksgiving dear @joeyvee1986 - I figured it out, I was building the docker image from /docker folder instead of /guix and then wondering where guix went... *facepalm*
