### ISSUE TITLE
how to run bitcoin unittests + functional tests with sanitizers

### ISSUE THREAD

**Issue by elichai** [fanquake/core-review#8]
Hi,
a small guide from ground up on how to run sanitizers(asan/ubsan/msan) on core would be awesome :)
@practicalswift ;)

**Comment by MarcoFalke** [comment]
This should be in the main repo

**Comment by elichai** [comment]
> This should be in the main repo

good idea.

**Comment by fanquake** [comment]
Going to close this. I've added some docs in /fuzzing/ and there is more information being added to the main repo now.
